import HeartIcon from "@/public/icons/heart-svgrepo-com.svg";
import PlusIcon from "@/public/icons/Plus.svg";
import SettingsIcon from "@/public/icons/settings-svgrepo-com.svg";
import XSmallIcon from "@/public/icons/XSmall.svg";
import ChevronSmallIcon from "@/public/icons/ChevronSmall.svg";
import ArrowLeftIcon from "@/public/icons/ArrowSmall.svg";

import BookUserIcon from "@/public/icons/svg/notebook-alt_9795395.svg";
import PeopleIcon from "@/public/icons/svg/employees_14644298.svg";
import PotIcon from "@/public/icons/svg/pot_7409547.svg";
import PartyIcon from "@/public/icons/svg/party-horn_10470647.svg";
import PanIcon from "@/public/icons/svg/plate_7409529.svg";
import PenIcon from "/public/icons/svg/pen-square_10435869.svg";
import LeaveIcon from "@/public/icons/svg/arrow-left-from-line_9253329.svg";
import TrashIcon from "/public/icons/svg/trash-xmark_10741775.svg";
import CheckIcon from "@/public/icons/svg/check-circle_10470513.svg";
import CalenderIcon from "@/public/icons/svg/calendar-days_9795297.svg";
import BookIcon from "@/public/icons/svg/notebook-alt_9795395.svg";
import ArrowUpIcon from "@/public/icons/svg/arrow-alt-up_7434980.svg";
import GenerateIcon from "@/public/icons/svg/pen-swirl_10741646.svg";
import SaveShoppingIcon from "@/public/icons/svg/cart-arrow-down_9795299.svg";

export const ArrowUp = ArrowUpIcon;
export const ArrowLeft = ArrowLeftIcon;
export const BookUser = BookUserIcon;
export const Book = BookIcon;
export const Calender = CalenderIcon;
export const Check = CheckIcon;
export const ChevronSmall = ChevronSmallIcon;
export const Generate = GenerateIcon;
export const Heart = HeartIcon;
export const Leave = LeaveIcon;
export const Pan = PanIcon;
export const Party = PartyIcon;
export const Pen = PenIcon;
export const People = PeopleIcon;
export const Pot = PotIcon;
export const Plus = PlusIcon;
export const SaveShopping = SaveShoppingIcon;
export const Settings = SettingsIcon;
export const Trash = TrashIcon;
export const XSmall = XSmallIcon;
