import HeartIcon from "@/public/icons/heart-svgrepo-com.svg";
import PlusIcon from "@/public/icons/Plus.svg";
import SettingsIcon from "@/public/icons/settings-svgrepo-com.svg";
import XSmallIcon from "@/public/icons/XSmall.svg";
import ArrowSmallLeftIcon from "@/public/icons/arrow-small-left_10513360.svg";
import ArrowSmallRightIcon from "@/public/icons/arrow-small-right_10513361.svg";
import ChevronSmallIcon from "@/public/icons/ChevronSmall.svg";
import ArrowLeftIcon from "@/public/icons/ArrowSmall.svg";
import ReloadIcon from "@/public/icons/reload-svgrepo-com.svg";
import TriangleLeftIcon from "@/public/icons/arrow-left-3-svgrepo-com.svg";
import TriangleRightIcon from "@/public/icons/arrow-right-2-svgrepo-com.svg";
import EditIcon from "@/public/icons/edit-3-svgrepo-com (2).svg";
import FilterIcon from "@/public/icons/sliders-v_10435878.svg";

import BookUserIcon from "@/public/icons/svg/notebook-alt_9795395.svg";
import PeopleIcon from "@/public/icons/svg/employees_14644298.svg";
import PotIcon from "@/public/icons/svg/pot_7409547.svg";
import PartyIcon from "@/public/icons/svg/party-horn_10470647.svg";
import PanIcon from "@/public/icons/svg/plate_7409529.svg";
import PenIcon from "/public/icons/svg/pen-square_10435869.svg";
import LeaveIcon from "@/public/icons/svg/arrow-left-from-line_9253329.svg";
import TrashIcon from "/public/icons/svg/trash-xmark_10741775.svg";
import CheckIcon from "@/public/icons/svg/check-circle_10470513.svg";
import CalenderIcon from "@/public/icons/svg/calendar-days_9795297.svg";
import BookIcon from "@/public/icons/svg/notebook-alt_9795395.svg";
import ArrowUpIcon from "@/public/icons/svg/arrow-alt-up_7434980.svg";
import GenerateIcon from "@/public/icons/svg/pen-swirl_10741646.svg";
import SaveShoppingIcon from "@/public/icons/svg/cart-arrow-down_9795299.svg";
import BellIcon from "/public/icons/svg/cowbell_9083627.svg";
import MenuIcon from "/public/icons/svg/menu.svg";
import SearchIcon from "@/public/icons/svg/pan_7409478.svg";
import PlateIcon from "@/public/icons/svg/plate-and-utensils-top-view-svgrepo-com.svg";
import MinusIcon from "/public/icons/svg/horizontal-rule_9272854.svg";
import ShoppingIcon from "../public/icons/svg/square-u_10457596.svg";
import PizzaIcon from "../public/icons/svg/restaurant_7409576.svg";
import ProfileIcon from "../public/icons/svg/profile.svg";
import PlateWheelIcon from "/public/icons/svg/plate-wheel.svg";

export const ArrowUp = ArrowUpIcon;
export const ArrowLeft = ArrowLeftIcon;
export const ArrowSmallLeft = ArrowSmallLeftIcon;
export const ArrowSmallRight = ArrowSmallRightIcon;
export const Bell = BellIcon;
export const BookUser = BookUserIcon;
export const Book = BookIcon;
export const Calendar = CalenderIcon;
export const Check = CheckIcon;
export const ChevronSmall = ChevronSmallIcon;
export const Edit = EditIcon;
export const Filter = FilterIcon;
export const Generate = GenerateIcon;
export const Heart = HeartIcon;
export const Leave = LeaveIcon;
export const Menu = MenuIcon;
export const Minus = MinusIcon;
export const Pan = PanIcon;
export const Party = PartyIcon;
export const Pen = PenIcon;
export const People = PeopleIcon;
export const Pot = PotIcon;
export const Plate = PlateIcon;
export const PlateWheel = PlateWheelIcon;
export const Plus = PlusIcon;
export const Pizza = PizzaIcon;
export const Profile = ProfileIcon;
export const Reload = ReloadIcon;
export const SaveShopping = SaveShoppingIcon;
export const Search = SearchIcon;
export const Settings = SettingsIcon;
export const Shopping = ShoppingIcon;
export const Trash = TrashIcon;
export const TriangleLeft = TriangleLeftIcon;
export const TriangleRight = TriangleRightIcon;
export const XSmall = XSmallIcon;
